### ISSUE TITLE
Przypomnienie hasła

### ISSUE THREAD

**Issue by themalek** [stasiu20/ssorder#2]
Brak możliwości przypomnienia hasła.

**Comment by stasiu20** [comment]
To będzie pewnie gdzieś obok zmiany hasła

**Comment by stasiu20** [comment]
Myślę, że wystarczy zmiana hasła. Zamykam tego issua

**Comment by morawskim** [comment]
Funkcjionalność jest, ale maile nie dochodzą.

**Comment by themalek** [comment]
@stasiu20 żądam wyjaśnień albo będą potrącenia z eurogąbek.

**Comment by stasiu20** [comment]
Więc jak funkcjonalność jest to zamykam ten ticket, i trzeba otworzyć nowy dotyczący wysyłąnia maili
