### ISSUE TITLE
Numery pozycji z ulotki

### ISSUE THREAD

**Issue by themalek** [stasiu20/ssorder#3]
Można dodac numery z ultoki do właściwego zamówienia, żeby można było łatwiej zamawiać.

**Comment by stasiu20** [comment]
trzeba będzie dodać taki row w tabeli, tylko, że nie każda restauracja na ulotkach ma numery dań

**Comment by themalek** [comment]
Kolumna będzie INTowa i akceptować nulle. Jak nie będzie numerka dla szamy to wyświetlimy puste i też pewnie będzie ok. Poza tym, cała restauracja nie ma numerków to na danej restauracji nie printujemy tej kolumny.
