### ISSUE TITLE
Dodać nazwę użytkownika do "Zrealizowane"

### ISSUE THREAD

**Issue by themalek** [stasiu20/ssorder#4]
Można dodać nazwę usera, który zrealizował zamówienie.

**Comment by stasiu20** [comment]
można, i na pewno jeszcze przy realizacji trzeba dodać wyświetlanie kto to zamawiał bo na razie tego nie ma, a będzie przydatne

**Comment by themalek** [comment]
Można fajnie przedstawić kto zamówił a kto jeszcze nie, to nawet można się przed dokonaniem zamówienia upewnić czy te osoby na pewno nie chcą.

**Comment by morawskim** [comment]
Kolumna kto zamowil zostala dodana.
Zamykam zgloszenie.
