### ISSUE TITLE
Statystyki dania

### ISSUE THREAD

**Issue by stasiu20** [stasiu20/ssorder#6]
Trzeba będzie dodać plusy i minusy do oceniania dania, i oraz komentarze.

**Comment by themalek** [comment]
Jeszcze można by zrobić fajną opcję po zalogowaniu np. pytanie "To co zawsze ?" - pod spodem podane z jakiej restauracji i co ktoś najczęściej zamawia i przycisk. Przycisk zabiera do tego dania (a raczej od razu do edycji, gdzie można klepnąć sosy itd.)

**Comment by stasiu20** [comment]
Spoko opcja :D
